export default [
  { name: 'アラビア語', value: 'ar' },
  { name: '簡体字', value: 'zh-CN' },
  { name: '繁体字', value: 'zh-TW' },
  { name: '英語', value: 'en' },
  { name: 'エスペラント', value: 'eo' },
  { name: 'フランス語', value: 'fr' },
  { name: 'ドイツ語', value: 'de' },
  { name: 'ヒンディー語', value: 'hi' },
  { name: 'イタリア語', value: 'it' },
  { name: '日本語', value: 'ja' },
  { name: '韓国語', value: 'ko' },
  { name: 'ラテン語', value: 'la' },
  { name: 'ロシア語', value: 'ru' },
  { name: 'スペイン語', value: 'es' },
]
